wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.5
    session_history: code/_session_history.ipynb
beta:
  desc: null
  value: 5
dim:
  desc: null
  value: 64
lr:
  desc: null
  value: 0.01
